const projects={
jarvis:{k:'01 / AI / PYTHON',t:'JARVIS AI',d:'A working personal AI assistant built with Python, Streamlit and Gemini. The system is being extended toward voice interaction, file analysis, memory and SOC assistance.',s:['Python','Streamlit','Gemini AI','AI Assistant'],repo:'https://github.com/jalex00565-rgb/JarvisAI'},
soc:{k:'02 / CYBERSECURITY',t:'MINI SOC INCIDENT ANALYZER',d:'A security-analysis workflow that converts raw logs into detections, risk assessment, investigation context and incident reporting — the core workflow of a practical SOC tool.',s:['Log Analysis','Detection','Risk Scoring','Incident Reporting'],repo:'https://github.com/jalex00565-rgb/SOC-Incident-Analyzer'},
localai:{k:'03 / PLANNED',t:'LOCAL AI SECURITY ASSISTANT',d:'An offline AI layer planned for document analysis and a cybersecurity knowledge base, with the long-term goal of integrating it into the Jarvis ecosystem.',s:['Ollama','LLM','Offline AI','Security Knowledge Base']}
};
const modal=document.querySelector('#modal'),mk=document.querySelector('#modalKicker'),mt=document.querySelector('#modalTitle'),md=document.querySelector('#modalText'),ms=document.querySelector('#modalStack');
document.querySelectorAll('.details').forEach(b=>b.onclick=()=>{let x=projects[b.dataset.project];mk.textContent=x.k;mt.textContent=x.t;md.textContent=x.d;ms.innerHTML=x.s.map(v=>`<span>${v}</span>`).join('')+(x.repo?`<a class="repo-link" href="${x.repo}" target="_blank" rel="noopener">VIEW GITHUB REPOSITORY ↗</a>`:'');modal.classList.add('open')});
document.querySelector('#close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.onkeydown=e=>{if(e.key==='Escape')modal.classList.remove('open')};
window.addEventListener('load',()=>setTimeout(()=>{document.querySelector('#loader').style.opacity='0';setTimeout(()=>document.querySelector('#loader').remove(),650)},900));
const links=document.querySelectorAll('nav a');window.addEventListener('scroll',()=>{let y=scrollY;links.forEach(a=>{let s=document.querySelector(a.getAttribute('href'));a.style.color=s&&y>=s.offsetTop-130&&y<s.offsetTop+s.offsetHeight-130?'#75f5b4':''})});
